### ISSUE TITLE
Renaming containers

### ISSUE THREAD

**Issue by alexanderadam** [ContainerUp/containerup#15]
[`podman rename`](https://docs.podman.io/en/stable/markdown/podman-rename.1.html) allows to update the resource limits, too.

It would be nice if that would be possible via GUI.

I guess that this warning should be added then though:

> Running containers may not fully receive the effects until they are restarted - for example, a running container may still use the old name in its logs.

**Comment by yylyyl** [comment]
Renaming is a very routine task. It will be added in the version 0.1.0.

But I don't think that warning message necessary. It seems there is no way for a container to get its name without accessing the Podman API. And the container ID is not changed after renaming. Correct me if I'm wrong.
