### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by adam-kulagowski** [ContainerUp/containerup#34]
Is is possible to use ContainerUp with SSL certificates to encrypt browser traffic? Ideally without using another container for reverse proxy.

Regards,
Adam

**Comment by yylyyl** [comment]
That's a good idea, and will be implemented very soon.

**Comment by yylyyl** [comment]
This feature has been implemented, and is released in [v0.1.0-rc2](https://github.com/ContainerUp/containerup/releases/tag/v0.1.0-rc2).

Consult the [documents](https://containerup.org/configurations/#containerup_tls_cert) about how to enable TLS.

**Comment by adam-kulagowski** [comment]
Thanks 👍

**Comment by adam-kulagowski** [comment]
Tested and I can confirm - working as expected.

 A small note to the documentation might added that SSL version uses the same port 3876 as non-SSL version.
